# integrations:
#   github_exporter:
#     api_token: <your github api token>
#     enabled: true
#     repositories:
#       - grafana/agent
#   postgres_exporter:
#     data_source_names:
#       - postgresql://root@localhost:5432
#     enabled: true
#   prometheus_remote_write:
#     - basic_auth:
#         password: bla
#         username: 123
#       url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
prometheus:
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: bla
            username: 123
          url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
      scrape_configs:
        - job_name: apollo-server-integration
          static_configs:
            - targets: ['backend:80']
  global:
    scrape_interval: 60s
  # wal_directory: /tmp/grafana-agent-wal
# server:
#   http_listen_port: 12345